name: dart_gen_extra
description: A package that simplifies the generation of additional features
version: 0.0.1
maintainer: Dmitriy Trofimov
homepage: https://github.com/a-dev-mobile/dart_gen_extra
repository: https://github.com/a-dev-mobile/dart_gen_extra/
issue_tracker: https://github.com/a-dev-mobile/dart_gen_extra/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: any
  args: any
  cli_util: any
  collection: any
  yaml: any
  intl: any
dev_dependencies:
  lints: ^2.0.1

dart_gen_extra:
  assets_output: "lib/gen/" 
